apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-ngdz
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-12-tenant/test-rhtap-12-app/devfile-sample-code-with-quarkus-ngdz@sha256:72fe1f7a088acdee37b942c4b60f5b41f4dec5482100deaa42805d1a247adc80
        name: my-java-quarkus
        resources: {}
status: {}
